import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gray">
        <main className="min-h-[100vh] max-w-[1280px] w-full bg-white  pl-[100px] pr-[50px] m-auto flex ">
          <div className="h-full min-h-[720px] grid grid-cols-5 gap-[50px] pt-[100px]">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
