import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="bg-gray flex justify-center items-center h-full">
          <main className="flex py-[3.125rem] px-[3.125rem] h-full w-full flex-col lg:flex-row max-w-[80rem] min-h-screen bg-white">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
