import './globals.css';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <head>
                <link href="themes/one-dark.css" rel="stylesheet" />
            </head>
            <body className="bg-gray">
                <main className="min-h-[100vh] max-w-[1280px] w-full bg-white  min-[1200px]:pl-[100px] min-[1200px]:pr-[50px] p-[25px] m-auto flex ">
                    <div className="w-full h-full min-h-[720px] grid grid-cols-[repeat(auto-fit,minmax(180px,1fr))] gap-[50px] min-[1200px]:pt-[100px]">
                        {children}
                    </div>
                </main>
            </body>
        </html>
    );
}
